// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chienha0903/Todo_App/services/todos/internal/config"
	grpc2 "github.com/chienha0903/Todo_App/services/todos/internal/handler/grpc"
	todohandler "github.com/chienha0903/Todo_App/services/todos/internal/handler/grpc/todo"
	"github.com/chienha0903/Todo_App/services/todos/internal/domain/service"
	"github.com/chienha0903/Todo_App/services/todos/internal/infra/datastore"
	"google.golang.org/grpc"
)

// InitGRPCServer wires all dependencies and returns a ready *grpc.Server.
func InitGRPCServer(cfg *config.Config) (*grpc.Server, error) {
	pool, err := datastore.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	todoRepo := datastore.NewTodoRepo(pool)
	todoCreater := service.NewTodoCreater(todoRepo)
	todoGetter := service.NewTodoGetter(todoRepo)
	todoLister := service.NewTodoLister(todoRepo)
	todoUpdater := service.NewTodoUpdater(todoRepo, todoRepo)
	todoDeleter := service.NewTodoDeleter(todoRepo)
	todoHandler := todohandler.NewTodoHandler(todoCreater, todoGetter, todoLister, todoUpdater, todoDeleter)
	server := grpc2.NewGRPCServer(todoHandler)
	return server, nil
}
