// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chienha0903/Todo_App/services/todos/internal/config"
	"github.com/chienha0903/Todo_App/services/todos/internal/domain/service"
	grpc2 "github.com/chienha0903/Todo_App/services/todos/internal/handler/grpc"
	"github.com/chienha0903/Todo_App/services/todos/internal/handler/grpc/todo"
	"github.com/chienha0903/Todo_App/services/todos/internal/infra/datastore"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

// InitGRPCServer wires all dependencies and returns a ready *grpc.Server.
func InitGRPCServer(cfg *config.Config) (*grpc.Server, error) {
	pool, err := datastore.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	todoRepo := datastore.NewTodoRepo(pool)
	todoCommandGateway := datastore.NewTodoCommandGateway(todoRepo)
	todoCreator := service.NewTodoCreator(todoCommandGateway)
	todoQueryGateway := datastore.NewTodoQueryGateway(todoRepo)
	todoGetter := service.NewTodoGetter(todoQueryGateway)
	todoLister := service.NewTodoLister(todoQueryGateway)
	todoUpdater := service.NewTodoUpdater(todoCommandGateway, todoQueryGateway)
	todoDeleter := service.NewTodoDeleter(todoCommandGateway)
	todoHandler := todo.NewTodoHandler(todoCreator, todoGetter, todoLister, todoUpdater, todoDeleter)
	server := grpc2.NewGRPCServer(todoHandler)
	return server, nil
}
