// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chienha0903/Todo_App/services/todos/internal/config"
	"github.com/chienha0903/Todo_App/services/todos/internal/domain/service"
	grpc2 "github.com/chienha0903/Todo_App/services/todos/internal/handler/grpc"
	"github.com/chienha0903/Todo_App/services/todos/internal/handler/grpc/todo"
	"github.com/chienha0903/Todo_App/services/todos/internal/infra/datastore"
	"google.golang.org/grpc"
)

func InitializeApp(cfg *config.Config) (*grpc.Server, func(), error) {
	db, cleanup, err := datastore.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	todoCommandRepo := datastore.NewTodoCommandRepo(db)
	todoCommandGateway := datastore.NewTodoCommandGateway(todoCommandRepo)
	todoCreater := service.NewTodoCreater(todoCommandGateway)
	todoQueryRepo := datastore.NewTodoQueryRepo(db)
	todoQueryGateway := datastore.NewTodoQueryGateway(todoQueryRepo)
	todoGetter := service.NewTodoGetter(todoQueryGateway)
	todoLister := service.NewTodoLister(todoQueryGateway)
	todoUpdater := service.NewTodoUpdater(todoCommandGateway, todoQueryGateway)
	todoDeleter := service.NewTodoDeleter(todoCommandGateway)
	todoHandler := todo.NewTodoHandler(todoCreater, todoGetter, todoLister, todoUpdater, todoDeleter)
	server := grpc2.NewGRPCServer(todoHandler)
	return server, cleanup, nil
}
