// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chienha0903/Todo_App/services/users/internal/config"
	"github.com/chienha0903/Todo_App/services/users/internal/domain/service"
	grpc2 "github.com/chienha0903/Todo_App/services/users/internal/handler/grpc"
	"github.com/chienha0903/Todo_App/services/users/internal/handler/grpc/user"
	"github.com/chienha0903/Todo_App/services/users/internal/infra/datastore"
	"github.com/chienha0903/Todo_App/services/users/internal/infra/redis"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*grpc.Server, func(), error) {
	db, cleanup, err := datastore.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	userCommandRepo := datastore.NewUserCommandRepo(db)
	userCommandGateway := datastore.NewUserCommandGateway(userCommandRepo)
	userCreater := service.NewUserCreater(userCommandGateway)
	userQueryRepo := datastore.NewUserQueryRepo(db)
	userQueryGateway := datastore.NewUserQueryGateway(userQueryRepo)
	userGetter := service.NewUserGetter(userQueryGateway)
	userBatchGetter := service.NewUserBatchGetter(userQueryGateway)
	userLister := service.NewUserLister(userQueryGateway)
	gormTransactor := datastore.NewGormTransactor(db)
	userUpdater := service.NewUserUpdater(userCommandGateway, userQueryGateway, gormTransactor)
	outboxRepo := datastore.NewOutboxRepo(db)
	outboxCommandGateway := datastore.NewOutboxCommandGateway(outboxRepo)
	userDeleter := service.NewUserDeleter(userCommandGateway, userQueryGateway, outboxCommandGateway, gormTransactor)
	client, cleanup2, err := redisstore.NewClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	refreshTokenRepo := redisstore.NewRefreshTokenRepo(client)
	refreshTokenCommandGateway := redisstore.NewRefreshTokenCommandGateway(refreshTokenRepo)
	userAuthenticator := service.NewUserAuthenticator(userQueryGateway, refreshTokenCommandGateway, cfg)
	refreshTokenQueryGateway := redisstore.NewRefreshTokenQueryGateway(refreshTokenRepo)
	userRefresher := service.NewUserRefresher(refreshTokenCommandGateway, refreshTokenQueryGateway, cfg)
	userPasswordChanger := service.NewUserPasswordChanger(userQueryGateway, userCommandGateway, outboxCommandGateway, gormTransactor)
	userHandler := user.NewUserHandler(userCreater, userGetter, userBatchGetter, userLister, userUpdater, userDeleter, userAuthenticator, userRefresher, userPasswordChanger)
	server := grpc2.NewGRPCServer(cfg, userHandler)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}
