apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todo-app
type: Opaque
stringData:
  JWT_SECRET: "chien-apvn-super-secret-key-2024-abc"
  DB_USERS_DSN: "postgres://postgres:postgres@postgres-users-svc:5432/user_db?sslmode=disable"
  DB_TODO_DSN: "postgres://postgres:postgres@postgres-todo-svc:5432/todo_db?sslmode=disable"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-svc:5672/"
  REDIS_URL: "redis://redis-svc:6379/0"
