// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/config"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/domain/service"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/resolver"
	infratodo "github.com/chienha0903/Todo_App/services/todo-bff/internal/infra/todo"
)

func InitializeApp(cfg *config.Config) (*resolver.Resolver, func(), error) {
	conn, cleanup, err := infratodo.NewGRPCConn(cfg)
	if err != nil {
		return nil, nil, err
	}
	client := infratodo.NewTodoServiceClient(conn)
	gw := infratodo.NewGRPCGateway(client)
	todoCreater := service.NewTodoCreater(gw)
	todoGetter := service.NewTodoGetter(gw)
	todoLister := service.NewTodoLister(gw)
	todoUpdater := service.NewTodoUpdater(gw)
	todoDeleter := service.NewTodoDeleter(gw)
	gqlResolver := resolver.NewResolver(cfg, todoCreater, todoGetter, todoLister, todoUpdater, todoDeleter)
	return gqlResolver, cleanup, nil
}
