// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/config"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/domain/service"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/resolver"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/infra/todo"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*resolver.Resolver, func(), error) {
	clientConn, cleanup, err := todo.NewGRPCConn(cfg)
	if err != nil {
		return nil, nil, err
	}
	todoServiceClient := todo.NewTodoServiceClient(clientConn)
	todoGateway := todo.NewGRPCGateway(todoServiceClient)
	todoCreater := service.NewTodoCreater(todoGateway)
	todoGetter := service.NewTodoGetter(todoGateway)
	todoLister := service.NewTodoLister(todoGateway)
	todoUpdater := service.NewTodoUpdater(todoGateway)
	todoDeleter := service.NewTodoDeleter(todoGateway)
	resolverResolver := resolver.NewResolver(cfg, todoCreater, todoGetter, todoLister, todoUpdater, todoDeleter)
	return resolverResolver, func() {
		cleanup()
	}, nil
}
