// Code generated by MockGen. DO NOT EDIT.
// Source: services/todos/internal/domain/gateway/todo.go
//
// Generated by this command:
//
//	mockgen -source=services/todos/internal/domain/gateway/todo.go -destination=services/todos/internal/domain/gateway/mock/mock_todo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/chienha0903/Todo_App/services/todos/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoCommandGateway is a mock of TodoCommandGateway interface.
type MockTodoCommandGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCommandGatewayMockRecorder
	isgomock struct{}
}

// MockTodoCommandGatewayMockRecorder is the mock recorder for MockTodoCommandGateway.
type MockTodoCommandGatewayMockRecorder struct {
	mock *MockTodoCommandGateway
}

// NewMockTodoCommandGateway creates a new mock instance.
func NewMockTodoCommandGateway(ctrl *gomock.Controller) *MockTodoCommandGateway {
	mock := &MockTodoCommandGateway{ctrl: ctrl}
	mock.recorder = &MockTodoCommandGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCommandGateway) EXPECT() *MockTodoCommandGatewayMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoCommandGateway) CreateTodo(ctx context.Context, todo *entity.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoCommandGatewayMockRecorder) CreateTodo(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoCommandGateway)(nil).CreateTodo), ctx, todo)
}

// DeleteTodo mocks base method.
func (m *MockTodoCommandGateway) DeleteTodo(ctx context.Context, id entity.TodoID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoCommandGatewayMockRecorder) DeleteTodo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoCommandGateway)(nil).DeleteTodo), ctx, id)
}

// UpdateTodo mocks base method.
func (m *MockTodoCommandGateway) UpdateTodo(ctx context.Context, todo *entity.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoCommandGatewayMockRecorder) UpdateTodo(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoCommandGateway)(nil).UpdateTodo), ctx, todo)
}

// MockTodoQueryGateway is a mock of TodoQueryGateway interface.
type MockTodoQueryGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoQueryGatewayMockRecorder
	isgomock struct{}
}

// MockTodoQueryGatewayMockRecorder is the mock recorder for MockTodoQueryGateway.
type MockTodoQueryGatewayMockRecorder struct {
	mock *MockTodoQueryGateway
}

// NewMockTodoQueryGateway creates a new mock instance.
func NewMockTodoQueryGateway(ctrl *gomock.Controller) *MockTodoQueryGateway {
	mock := &MockTodoQueryGateway{ctrl: ctrl}
	mock.recorder = &MockTodoQueryGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoQueryGateway) EXPECT() *MockTodoQueryGatewayMockRecorder {
	return m.recorder
}

// GetTodo mocks base method.
func (m *MockTodoQueryGateway) GetTodo(ctx context.Context, id entity.TodoID) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo", ctx, id)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoQueryGatewayMockRecorder) GetTodo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoQueryGateway)(nil).GetTodo), ctx, id)
}

// GetTodos mocks base method.
func (m *MockTodoQueryGateway) GetTodos(ctx context.Context, userID entity.UserID) ([]*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodos", ctx, userID)
	ret0, _ := ret[0].([]*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodos indicates an expected call of GetTodos.
func (mr *MockTodoQueryGatewayMockRecorder) GetTodos(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodos", reflect.TypeOf((*MockTodoQueryGateway)(nil).GetTodos), ctx, userID)
}
