package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"

	todograph "github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/generated"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/model"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/mapper"
	todopb "github.com/chienha0903/Todo_App/proto/todo"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.Todo, error) {
	dueDate, err := mapper.ParseOptionalDueDate(input.DueDate)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	resp, err := r.todoClient.CreateTodo(ctx, &todopb.CreateTodoRequest{
		UserId:      int64(input.UserID),
		Title:       input.Title,
		Description: input.Description,
		Priority:    input.Priority,
		DueDate:     dueDate,
	})
	if err != nil {
		return nil, todograph.ToGraphQLError(err)
	}

	return mapper.ToModel(resp.GetTodo()), nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodoInput) (*model.Todo, error) {
	todoID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	dueDate, err := mapper.ParseOptionalDueDate(input.DueDate)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	req := &todopb.UpdateTodoRequest{Id: todoID}
	if input.Title != nil {
		req.Title = *input.Title
	}
	if input.Description != nil {
		req.Description = *input.Description
	}
	if input.Priority != nil {
		req.Priority = *input.Priority
	}
	if input.Status != nil {
		req.Status = *input.Status
	}
	req.DueDate = dueDate

	resp, err := r.todoClient.UpdateTodo(ctx, req)
	if err != nil {
		return nil, todograph.ToGraphQLError(err)
	}

	return mapper.ToModel(resp.GetTodo()), nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	todoID, err := parseID(id)
	if err != nil {
		return false, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	_, err = r.todoClient.DeleteTodo(ctx, &todopb.DeleteTodoRequest{Id: todoID})
	if err != nil {
		return false, todograph.ToGraphQLError(err)
	}

	return true, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	todoID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	resp, err := r.todoClient.GetTodo(ctx, &todopb.GetTodoRequest{Id: todoID})
	if err != nil {
		return nil, todograph.ToGraphQLError(err)
	}

	return mapper.ToModel(resp.GetTodo()), nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, userID int) ([]*model.Todo, error) {
	if userID <= 0 {
		return nil, fmt.Errorf("invalid argument: userId must be a positive integer")
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	resp, err := r.todoClient.ListTodos(ctx, &todopb.ListTodosRequest{UserId: int64(userID)})
	if err != nil {
		return nil, todograph.ToGraphQLError(err)
	}

	return mapper.ToModels(resp.GetTodos()), nil
}

func parseID(id string) (int64, error) {
	parsed, err := strconv.ParseInt(id, 10, 64)
	if err != nil || parsed <= 0 {
		return 0, fmt.Errorf("invalid argument: id must be a positive integer")
	}
	return parsed, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
