package resolver

// Code generated by github.com/99designs/gqlgen version v0.17.90

import "github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/generated"

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
