package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"

	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/generated"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/model"
	ucin "github.com/chienha0903/Todo_App/services/todo-bff/internal/usecase/todo/input"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.Todo, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	todo, err := r.creater.Create(ctx, &ucin.CreateTodo{
		UserID:      int64(input.UserID),
		Title:       input.Title,
		Description: input.Description,
		Priority:    input.Priority,
		DueDate:     derefStr(input.DueDate),
	})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toModel(todo), nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodoInput) (*model.Todo, error) {
	todoID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	todo, err := r.updater.Update(ctx, &ucin.UpdateTodo{
		ID:          todoID,
		Title:       derefStr(input.Title),
		Description: derefStr(input.Description),
		Priority:    derefStr(input.Priority),
		Status:      derefStr(input.Status),
		DueDate:     derefStr(input.DueDate),
	})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toModel(todo), nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	todoID, err := parseID(id)
	if err != nil {
		return false, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	if err := r.deleter.Delete(ctx, &ucin.DeleteTodo{ID: todoID}); err != nil {
		return false, toGraphQLError(err)
	}
	return true, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	todoID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	todo, err := r.getter.Get(ctx, &ucin.GetTodo{ID: todoID})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toModel(todo), nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, userID int) ([]*model.Todo, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	todos, err := r.lister.List(ctx, &ucin.ListTodos{UserID: int64(userID)})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toModels(todos), nil
}

func parseID(id string) (int64, error) {
	parsed, err := strconv.ParseInt(id, 10, 64)
	if err != nil || parsed <= 0 {
		return 0, fmt.Errorf("invalid argument: id must be a positive integer")
	}
	return parsed, nil
}

func derefStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
