package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/graph/model"
	"github.com/chienha0903/Todo_App/services/todo-bff/internal/handler/middleware"
	ucin "github.com/chienha0903/Todo_App/services/todo-bff/internal/usecase/user/input"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	tokens, err := r.userGateway.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		AccessToken:  tokens.AccessToken,
		RefreshToken: tokens.RefreshToken,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthPayload, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	tokens, err := r.userGateway.RefreshToken(ctx, &ucin.RefreshToken{
		RefreshToken: input.RefreshToken,
	})

	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  tokens.AccessToken,
		RefreshToken: tokens.RefreshToken,
	}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (bool, error) {
	if err := middleware.RequireAuth(ctx); err != nil {
		return false, err
	}
	userID, _ := middleware.GetUserID(ctx)

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	if err := r.userGateway.ChangePassword(ctx, &ucin.ChangePassword{
		UserID:          userID,
		CurrentPassword: input.CurrentPassword,
		NewPassword:     input.NewPassword,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	u, err := r.userGateway.UpdateUser(ctx, &ucin.UpdateUser{
		ID:       userID,
		Email:    derefStr(input.Email),
		Username: derefStr(input.Username),
		Password: derefStr(input.Password),
		Role:     derefStr(input.Role),
	})
	if err != nil {
		return nil, err
	}
	return toUserModel(u), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	if err := requireAdmin(ctx); err != nil {
		return false, err
	}

	userID, err := parseID(id)
	if err != nil {
		return false, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	if err := r.userGateway.DeleteUser(ctx, &ucin.DeleteUser{ID: userID}); err != nil {
		return false, err
	}
	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	if err := middleware.RequireAuth(ctx); err != nil {
		return nil, err
	}

	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	u, err := r.userGateway.GetUser(ctx, &ucin.GetUser{ID: userID})
	if err != nil {
		return nil, err
	}
	return toUserModel(u), nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, page *int, pageSize *int) (*model.UserPage, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	p, ps := int32(1), int32(20)
	if page != nil && *page > 0 {
		p = int32(*page)
	}
	if pageSize != nil && *pageSize > 0 {
		ps = int32(*pageSize)
	}

	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	result, err := r.userGateway.ListUsers(ctx, &ucin.ListUsers{Page: p, PageSize: ps})
	if err != nil {
		return nil, err
	}
	return toUserPageModel(result), nil
}
