syntax = "proto3";

package user.v1;

option go_package = "github/chienha0903/Todo_App/proto/user;userpb";

service Userservice {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
    rpc GetUsersByIDs(GetUsersByIDsRequest) returns (GetUsersByIDsResponse);
    rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
    rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
    rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
}

message CreateUserRequest {
    string email = 1;
    string username = 2;
    string password = 3;
    string role = 4;
}

message CreateUserResponse {
    User user = 1;
}

message GetUserRequest {
    int64 id = 1;
}

message GetUserResponse {
    User user = 1;
}

message GetUsersByIDsRequest {
    repeated int64 ids = 1;
}

message GetUsersByIDsResponse {
    repeated User users = 1;
}

message ListUsersRequest {
    int32 page      = 1;
    int32 page_size = 2;
}

message ListUsersResponse {
    repeated User users = 1;
    int32 total         = 2;
    int32 page          = 3;
    int32 page_size     = 4;
}

message UpdateUserRequest {
    int64 id = 1;
    string email = 2;
    string username = 3;
    string password = 4;
    string role = 5;
}

message UpdateUserResponse {
    User user = 1;
}

message DeleteUserRequest {
    int64 id = 1;
}

message DeleteUserResponse {}

message User {
    int64 id = 1;
    string email = 2;
    string username = 3;
    string password_hash =4;
    string role = 5;
    string created_at = 6;
    string updated_at = 7;
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
    int64 access_token_expires = 3;
    int64 refresh_token_expires = 4;
}

message RefreshTokenRequest {
    string refresh_token = 1;
}

message RefreshTokenResponse {
    string access_token = 1;
    string refresh_token = 2;
    int64 access_token_expires = 3;
    int64 refresh_token_expires = 4;
}

message ChangePasswordRequest {
    int64  user_id          = 1;
    string current_password = 2;
    string new_password     = 3;
}

message ChangePasswordResponse {}
