name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Check code formatting (gofmt)
        run: make fmt-check

      - name : Check code linting (golangci-lint)
        run: make lint

      - name: Run go vet
        run: make vet

      - name: Run tests
        run: make test

      - name: Build all services
        run: make build
